CREATE
  TABLE PERSON
  (
    P_ID     NUMBER PRIMARY KEY,
    PNAME    VARCHAR2(100),
    USERNAME VARCHAR2(20),
    PASSWORD VARCHAR2(20),
    ADDRESS  VARCHAR2(250),
    DOB      DATE,
    GENDER   CHAR(1)
  );

CREATE
  TABLE SICK_PERSON
  (
    P_ID   NUMBER PRIMARY KEY,
    HS1_ID NUMBER,
    HS2_ID NUMBER
  );

CREATE
  TABLE WELL_PERSON
  (
    P_ID   NUMBER PRIMARY KEY,
    HS1_ID NUMBER,
    HS2_ID NUMBER
  );

CREATE
  TABLE DISEASE
  (
    D_ID  NUMBER PRIMARY KEY,
    DNAME VARCHAR2(50)
  );

CREATE
  TABLE RECORD_DISEASE
  (
    P_ID        NUMBER,
    D_ID        NUMBER,
    RECORD_TIME TIMESTAMP,
    PRIMARY KEY(P_ID, D_ID)
  );

CREATE
  TABLE DISEASE_OBSERVATION
  (
    D_ID    NUMBER,
    OB_TYPE VARCHAR2(50),
    PRIMARY KEY(D_ID, OB_TYPE)
  );

CREATE
  TABLE RECOMMENDATION
  (
    R_ID        NUMBER PRIMARY KEY,
    DESCRIPTION VARCHAR2(1024),
    FREQUENCY   VARCHAR2(20),
    LOWER_LIMIT VARCHAR2(20),
    UPPER_LIMIT VARCHAR2(20)
  );

CREATE
  TABLE STANDARD_RECOMMENDATION
  (
    D_ID      NUMBER,
    R_ID      NUMBER,
    RECO_TIME TIMESTAMP,
    PRIMARY KEY(D_ID, R_ID)
  );

CREATE
  TABLE SPECIFIC_RECOMMENDATION
  (
    P_ID      NUMBER,
    R_ID      NUMBER,
    RECO_TIME TIMESTAMP,
    PRIMARY KEY(P_ID, R_ID)
  );

CREATE
  TABLE ALERT
  (
    A_ID        NUMBER PRIMARY KEY,
    P_ID        NUMBER,
    DESCRIPTION VARCHAR2(1024)
  );

CREATE
  TABLE OBSERVATION
  (
    OB_ID    NUMBER PRIMARY KEY,
    OB_TYPE  VARCHAR2(50),
    OB_VALUE VARCHAR2(20)
  );

CREATE
  TABLE OBSERVATION_TYPE
  (
    OB_TYPE     VARCHAR2(50) PRIMARY KEY,
    FREQUENCY   VARCHAR2(20),
    DESCRIPTION VARCHAR2(1024),
    MEASURE     VARCHAR2(20),
    METRIC      VARCHAR2(20),
    LOWER_BOUND VARCHAR2(20),
    UPPER_BOUND VARCHAR2(20)
  );

CREATE
  TABLE RECORD_OBSERVATION
  (
    OB_ID       NUMBER,
    P_ID        NUMBER,
    RECORD_TIME TIMESTAMP,
    OB_TIME     TIMESTAMP,
    PRIMARY KEY(OB_ID, P_ID)
  );

ALTER TABLE SICK_PERSON ADD FOREIGN KEY (P_ID) REFERENCES PERSON(P_ID);
ALTER TABLE SICK_PERSON ADD FOREIGN KEY (HS1_ID) REFERENCES PERSON(P_ID);
ALTER TABLE SICK_PERSON ADD FOREIGN KEY (HS2_ID) REFERENCES PERSON(P_ID);
ALTER TABLE WELL_PERSON ADD FOREIGN KEY (P_ID) REFERENCES PERSON(P_ID);
ALTER TABLE WELL_PERSON ADD FOREIGN KEY (HS1_ID) REFERENCES PERSON(P_ID);
ALTER TABLE WELL_PERSON ADD FOREIGN KEY (HS2_ID) REFERENCES PERSON(P_ID);
ALTER TABLE RECORD_DISEASE ADD FOREIGN KEY (P_ID) REFERENCES PERSON(P_ID);
ALTER TABLE RECORD_DISEASE ADD FOREIGN KEY (D_ID) REFERENCES DISEASE(D_ID);
ALTER TABLE DISEASE_OBSERVATION ADD FOREIGN KEY (D_ID) REFERENCES DISEASE(D_ID);
ALTER TABLE DISEASE_OBSERVATION ADD FOREIGN KEY (OB_TYPE) REFERENCES OBSERVATION_TYPE(OB_TYPE);
ALTER TABLE STANDARD_RECOMMENDATION ADD FOREIGN KEY (D_ID) REFERENCES DISEASE(D_ID);
ALTER TABLE STANDARD_RECOMMENDATION ADD FOREIGN KEY (R_ID) REFERENCES RECOMMENDATION(R_ID);
ALTER TABLE SPECIFIC_RECOMMENDATION ADD FOREIGN KEY (P_ID) REFERENCES PERSON(P_ID);
ALTER TABLE SPECIFIC_RECOMMENDATION ADD FOREIGN KEY (R_ID) REFERENCES RECOMMENDATION(R_ID);
ALTER TABLE ALERT ADD FOREIGN KEY (P_ID) REFERENCES PERSON(P_ID);
ALTER TABLE OBSERVATION ADD FOREIGN KEY (OB_TYPE) REFERENCES OBSERVATION_TYPE(OB_TYPE);
ALTER TABLE RECORD_OBSERVATION ADD FOREIGN KEY (OB_ID) REFERENCES OBSERVATION(OB_ID);
ALTER TABLE RECORD_OBSERVATION ADD FOREIGN KEY (P_ID) REFERENCES PERSON(P_ID);

COMMIT;